### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'json'

### ISSUE THREAD

**Issue by fn1y** [integraloftheday/Pebble-Imessager#13]
My Pebble will find my Mac on my network but won't connect. I keep getting error AttributeError: 'Request' object has no attribute 'json'.

Sorry if this is a stupid mistake on my part, I've found this tricky to set up.

**Comment by fn1y** [comment]
`Traceback (most recent call last):
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/[my username]/PebbleImessageServer/app.py", line 66, in getReplies
    postData = request.json
  File "/Users/[my username]/PebbleImessageServer/lib/python3.10/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'json'
::ffff:192.168.0.131 - - [2022-05-25 20:51:34] "POST /msg/api/v1/replies HTTP/1.1" 500 192 0.000621`

**Comment by fn1y** [comment]
Nevermind, the latest error is `::ffff:192.168.0.131 - - [2022-05-25 20:58:37] "POST /msg/api/v1/replies HTTP/1.1" 500 192 0.000591`

**Comment by fn1y** [comment]
Trying this on a brand new Pebble and still getting the error. Any way to fix this @integraloftheday ?

**Comment by integraloftheday** [comment]
Hello!
Can you confirm you have a config.json in your server folder? Additionally, did you go through the steps in **Watch App Configuration** and made sure both have the same key value.

**Comment by fn1y** [comment]
Hi! Yes, I have a config.json and have been through the above steps in Watch App Configuration. Just in case, I redid the key generation and reinserted it into my .json, and I'm still having the same error.

**Comment by integraloftheday** [comment]
Okay that’s good. What are you specifically doing on the watch when the
error occurs?

**Comment by fn1y** [comment]
I go to Settings > Data Fetch. My pebble gives me a “Server cannot be reached” error while the aforementioned appears in my Mac terminal at the exact same time.

**Comment by integraloftheday** [comment]
Are you using http or https? Sorry for all the questions just trying to
debug!

**Comment by fn1y** [comment]
Https, I'm using port forwarding for global access. No need to apologise!

**Comment by fn1y** [comment]
I think I should mention that before I set up port forwarding I was still getting the same error.

**Comment by integraloftheday** [comment]
By chance are you using the version of the app present on the rebble store? Or did you side load the version from the github.

**Comment by fn1y** [comment]
I actually have tried both, but right now I'm on the version side loaded from Github.

**Comment by integraloftheday** [comment]
The side loaded version from GitHub should be the one you want. This is odd, not an error I have encountered before. Could you share your config.json file, with the key field redacted.

**Comment by fn1y** [comment]
Alright, here it is
```
{
"key":"[redacted]",
"port":6969,
"quickReplies":{
	"on":"true", 
	"responses":[
		"<Voice>",
		"yes",
		"no",
		"<Keyboard>"	
	]
},
"contacts":[
	{
		"buddyName":"[redacted]",
		"displayName":"Mum" 
	}
]
}

```

**Comment by integraloftheday** [comment]
Everything looks good there... I don't have a current server set up right now, so I can't try to do a full debug until 6/11ish. 
If you wanted to try anything I would suggest putting: 
`print(request.data)`
in line 65 of `app.py` to see if there is anything in the request. 
Since I'm confused otherwise the request data is not being parsed or doesn't have json.

**Comment by fn1y** [comment]
Alright, here's what was printed (followed with the error)
`b'{"key":"[redacted]"}'`

**Comment by integraloftheday** [comment]
Is the key actually in an array, or is it how you redacted it? 
Is the key really "key":"Value" or "key":"[Value]"

**Comment by fn1y** [comment]
I redacted it like that, the key is actually "key":"value"

**Comment by fn1y** [comment]
Any updates? I understand this might be a tricky problem, I'm completely alright if it can't be fixed
