### ISSUE TITLE
Error fetching data in Pebble App

### ISSUE THREAD

**Issue by zip27** [integraloftheday/Pebble-Imessager#2]
I'm using Pebble Time with iOS, and I wanted to get a form of text-reply functionality. I followed the steps on the guide using a Mac OSX computer, and installed the server. I verified functionality of the server by following the steps, entering a web browser and checking for the 404 page, which I received. Because I wanted to use HTTPS, I also installed the proper certificate on iOS, which was then verified by iOS. Finally, I sideloaded the latest release of Pebble-Imessager on my Pebble Time. I entered in the correct the IP address for the first step, then inputted the correct key into the config.json file. Finally, upon starting the server, I clicked the "Data Fetch", and immediately received a long error on the Terminal window, as well as a general error message on the Pebble Time. Here is the error. If the formatting is bad, this link should also work: https://pastebin.com/KMruhQvR.

`Traceback (most recent call last):
    File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
        return handle(*args_tuple)
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
        with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/_ssl3.py", line 793, in wrap_socket
        return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/_ssl3.py", line 311, in __init__
        raise x
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/_ssl3.py", line 307, in __init__
        self.do_handshake()
    File "/Users/arve/PebbleImessageServer/lib/python3.8/site-packages/gevent/_ssl3.py", line 663, in do_handshake
        self._sslobj.do_handshake()
OSError: [Errno 0] Error
2020-10-31T20:55:05Z <Greenlet at 0x1087408c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x108b32ae0 o)> failed with OSError
`
Not sure what I did wrong here, but any help would be greatly appreciated. Thanks.

**Comment by integraloftheday** [comment]
Hello. This error looks like it a problem with the SSL certificate in particular it appears the installation on the phone did not completely work. To double check, this try to go to `https://YourIp:YourPort` on your phone and make sure you can get the "Not Found" message without an browser error or a message that says "This Connection is Not Private"
If you do encounter this error. Double check you can see the intalled profile in Settings in
General>Profile
and that you granted a "Full Trust for root certificates" in General>About>Certificate Trust Setting. 

Thank you. I hope this helps. If not reply and I'll be happy to try to help.

**Comment by zip27** [comment]
Thanks so much for your quick reply - you helped so much! Turns out the only problem was that the certificate was not configured to root access - after changing the settings in "Certificate Trust Settings", I was able to configure the server properly. This program is great - thanks so much for making it.
